version: "3.7"
services:
  pocketbase:
    build:
      context: .
      args:
        - VERSION=0.22.10 # <--------- Set the Pocketbase version here. It will be downloaded from their GitHub repo
    container_name: pocketbase
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY="${MEILI_MASTER_KEY}""
      - MEILI_HOST="${MEILI_HOST}"
    ports:
      - "${POCKETBASE_EXPOSED_PORT}:8090"
    volumes:
      - ${PATH_TO_DATA}:/pb_data
      - ${PATH_TO_PUBLIC}:/pb_public #optional
      - ${PATH_TO_HOOK}:/pb_hooks #optional
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  meilisearch:
    stdin_open: true
    tty: true
    ports:
      - ${MEILI_EXPOSED_PORT}:7700
    environment:
      - MEILI_MASTER_KEY="${MEILI_MASTER_KEY}""
    volumes:
      - ${MEILI_DATA_PATH}:/meili_data
    image: getmeili/meilisearch:v1.10