services:
  pocketbase:
    build: .
    container_name: pocketbase
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_HOST=http://meilisearch:7700
      - INDEXED_COLLECTION=${INDEXED_COLLECTION}
      - TARGETOS="linux"
      - TARGETARCH="x86"
    ports:
      - "${POCKETBASE_EXPOSED_PORT}:8090"
    volumes:
      - ${PATH_TO_DATA}:/pb_data
      - ${PATH_TO_PUBLIC}:/pb_public #optional
      - ${PATH_TO_HOOK}:/pb_hooks #optional
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pocketbase-meili-net
  meilisearch:
    stdin_open: true
    tty: true
    ports:
      - ${MEILI_EXPOSED_PORT}:7700
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS}
    volumes:
      - ${MEILI_DATA_PATH}:/meili_data
    image: getmeili/meilisearch:v1.10
    networks:
      - pocketbase-meili-net

networks:
  pocketbase-meili-net:
    name: pocketbase-meili-net
    driver: bridge